name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy myma - pulling
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR }}
          git reset --hard
          git pull origin main && composer install && composer update && php artisan optimize
          php artisan config:clear
          ./update_repo.sh
