name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy myma - pulling
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAycDnCQ6jw6gj95RDxvupIiOOhS+xe5hMBlwYQeP5QIorQ8VRDJtt
jRpOIoOIN5XbD8uLyg9dbLiieaHT6hz/9Wlu2mzM06qMReiQ0rrbk8QSQsV4Keq2WkeGP7
6QcY/BDr0lOybpj1SZorjFSVDEPqLO0ABXPLy4lJkWqZC/iBYXyGfwa3rHGIurbk2UKVyB
hT46kqG+51CwZYYi9tQ2Birrc7uRc8VqShTHW072j+juKeawKEadzDmAt1ay2drbqnlMCm
QmyBvDzaimC58V6Qjy93ODllVQrlPMK6XPs/5fpyPIZ7+TtB5dZEtJFeHvqCp3E3HgNtcm
adHGV0ZBy8aPWGq/W0YcnyhXl5kB0OZbTRoV0NbKuRFC46JkSGn4gqC6JuS4F7zAq0z3Kt
3F4QzXfpupAKdiG3HRKpXlEUtTMqEy2fm/H5iZwRkNWaiDxhOxwMnQuGh2TNXCnKQqzsb5
DTExiyXfdJTR/Sgw3vXSrrLN+YL1hL/KwWbVi/pTAAAFiHoQK8h6ECvIAAAAB3NzaC1yc2
EAAAGBAMnA5wkOo8OoI/eUQ8b7qSIjjoUvsXuYTAZcGEHj+UCKK0PFUQybbY0aTiKDiDeV
2w/Li8oPXWy4onmh0+oc//VpbtpszNOqjEXokNK625PEEkLFeCnqtlpHhj++kHGPwQ69JT
sm6Y9UmaK4xUlQxD6iztAAVzy8uJSZFqmQv4gWF8hn8Gt6xxiLq25NlClcgYU+OpKhvudQ
sGWGIvbUNgYq63O7kXPFakoUx1tO9o/o7inmsChGncw5gLdWstna26p5TApkJsgbw82opg
ufFekI8vdzg5ZVUK5TzCulz7P+X6cjyGe/k7QeXWRLSRXh76gqdxNx4DbXJmnRxldGQcvG
j1hqv1tGHJ8oV5eZAdDmW00aFdDWyrkRQuOiZEhp+IKguibkuBe8wKtM9yrdxeEM136bqQ
CnYhtx0SqV5RFLUzKhMtn5vx+YmcEZDVmog8YTscDJ0LhodkzVwpykKs7G+Q0xMYsl33SU
0f0oMN710q6yzfmC9YS/ysFm1Yv6UwAAAAMBAAEAAAGAGiOnC1JdP11Kg6ou+dnjOOwYbA
MY4KWDvBM0hVzvD0CXiGlJLfP5Rp3Q38Hg5SrCPhKmIuDIvuxRCKdB2IQ3WWl2llAgXZAs
KmaOVO8mwcdWglYpUmz5gUrhBuM+vafdYHZ7G2XYPty8Jwv/a5dORbs8RlC0/MaKt536BL
AfUJdkL2/gA1zd7L0z0c+1UYKNuWCtoA/atweKQy0U3Jvz/+qRpOX5W2GJet2kUp0xbsXE
DaO40Q8NJMeSeK5/75/eORuiArlmfaYktyH6n7AHCoQIrwdbkTAHSWsvbbucFEAHAEeCZt
7r+OKk6qbxXdq/hR5MCFvT2T1t8BrucMxrTw2tZ3RmAQ7eFp5akHuEnfZP4e/cClfWclzt
tVvV8Ctmt3CLFuxuhekPWOI8HCu1sEKxZGoviSZawqK0yu01ceoMyVZzSDZOnT3HqNFaGE
V5v6Pe2DfpwXpdESj3Q5pudFGihw5fkH+LwgHjdeiH33uHDFAjG+2fQpfLvgJsYHpJAAAA
wBTedh0h8nFK78C0lFCDmkiL5inDEZctzazXMsCuYQJArVYfDvZZcIJVZGWf1JCxNkYsrR
DadYOjraUPxKGTo/PhVkX4RA8bxOThlnQ6IqaqSHbYuR6oIkfyBGKzPVmGCh171AVbgogX
aSZyWzoq1hJobOsr2PE4zu7b5r57RCnpK/Mu7QKFvWMJxo2z0fH3cWc7BpyWgCZZIzTdxZ
DFqp01MnbqUqZ8do4+dskD9QlMfZNylypw9eLm+B3zJ4Se6wAAAMEA5qX8QR2HYv3zbNGP
fppnDsdi++4ZbCgOFBYSLqo56B/0elq6fVsP2njmfGf2hdljptIEFShNlnCtc/aNEBC6qb
2VUTmB++Ne+hTFb+uMB9Zp7YhUrWdPiB5seHfckLLG4SfzDmDDsH5XxHaUCS3uMcW9v0LZ
Bn5e3SrgaeUFo110pK7mkLs4eZCUMVeiPmL4Op/vR83d4OQaI8E+gknxbGHTkYOy3w1h6S
9ieAzivRZlj6/Kn2nbgUJBGAlt7Gz3AAAAwQDf7d6vNtkR0wB9GXwaysYclTiylo1Fxp3h
xZXH8tE5s1PMvlxiKsiJZlZV2QLDSMESkQFW/dxmiO2XyyrvYzs7c5oWkxdmiPdOacsNWs
G/clsR+N3dZtWp/OAOzTVRlrnpXuS3/a9pJ+FZ1yva7mg4/U4Nv5+6ToV9Xbh5ekK9Bteb
v3J3NF7sz4ZAhaohZ6x+pm0tQXlq8eCAVP5AeH4aTga9aCHQwRQ+221LhXAzcBkZXkNbhe
+WMk3w71jiEoUAAAAQcm9vdEB2cHMtdGVzdGluZwECAw==
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR }}
          git pull origin main && composer install && composer update && php artisan optimize
          php artisan config:clear
          ./update_repo.sh
